config/routes.rb
Producer::Application.routes.draw do
  

  resources :categories

  root :to => 'pages#index'
	
	resources :posts do
		resources :comments, :only => [:create]
	end
	get "pages/index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
	validates_presence_of :name
	
	has_and_belongs_to_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :title, :body, :author 
	validates_associated :author
	attr_accessible :title, :excerpt, :body, :author_id

  has_and_belongs_to_many :categories
  has_many :comments, :dependent => :destroy
  
  belongs_to :author, 
    :class_name => "User", 
    :foreign_key => "author_id"  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :post, foreign_key: "author_id"
  validates_presence_of :email, :first_name, :last_name
	validates_uniqueness_of :email
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	
	def full_name
		[first_name, last_name].join(" ")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])

    unless @comment.save
      flash[:alert] = "Fail to receive your comment."
    end
    redirect_to @post
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
	class PostsController < ApplicationController
	respond_to :html, :xml, :json
	include ActiveModel::MassAssignmentSecurity
	attr_accessible :category

	
	before_filter :load_resources, :only => %w(edit new update create)
	
  def index
    @posts = Post.all
    respond_with @posts
  end

  def show
    @post = Post.find(params[:id])

    respond_with @post
  end

  def new
    @post = Post.new

	respond_with @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
		flash[:notice] = "Post was succefully created."		
	end
	respond_with @post
  end

  def update
    @post = Post.find(params[:id])

    
	  if @post.update_attributes(params[:post])
			flash[:notice] = "Post was successfully updated"
	  end
		
		respond_with @post    
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
	
	private 
	
	def load_resources
		@authors = User.all
		@categories = Category.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def error_messages_for(resource)
	 render partial: "error_messages_for",
			locals: {resource: resource}
	end
	
	def flash_messages
		flash.collect do |key, msg|
			content_tag(:p, msg, :id => key, :class => "flash_message")
		end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<p>
		<%= comment.author %><br />	
		<%= comment.body %><br />	
		Posted <%= time_ago_in_words comment.created_at %> ago<br />	
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [ post, comment ] do |f| %>
  <%= error_messages_for comment %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Producer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash_messages.join.html_safe %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/posts/_error_messages_for.html.erb
<% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<%= error_messages_for @post %>
  <div class="field">
    <%= f.label :author_id, "Author" %><br />
    <%= f.collection_select :author_id, @authors, :id, :full_name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_area :excerpt, :rows => 10, :cols => 80 %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 50, :cols => 80 %>
  </div>
  <div class="field">
	<% @categories.each do |category| %>
		<label>
		<%= check_box_tag "post[category][]", category.id, @post.categories.include?(category) %>
		<%= category.name %>
		</label><br />
	<% end %>
  </div>
  <div class="actions">
    <%= f.submit :disable_with => "Wait..." %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if @posts.present? %>
	<% @posts.each do |post| %>
		<h2><%= link_to post.title.titleize, post %></h2>
		<div id="post">
			<%= post.excerpt %>
			<p><%= link_to "continue...", post %></p>
		</div>
		
		<p>
		<%= link_to "Edit", edit_post_path(post) %> | 
		<%= link_to "Destroy", post, :confirm => "Are you sure?", :delete => post %>
		</p>
		
		<hr />		
	<% end %>
<% else %>
	<p>We'll start posting soon.</p>
<% end %>
<p><%= link_to "New Post", new_post_path %></p>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<div id='post'>
  <%= @post.body %>
</div>

<hr />

<h3>Comments</h3>
<div id='comments'>
<% if @post.comments.any? %>
	<%= render @post.comments %>
<% else %>	
	<p>Nobody commented this post yet.</p>
<% end %>
</div>

<hr />
<%= render "comments/form", :post => @post, :comment => Comment.new %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>